routes/web.php
<?php


Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    // Route::group(['prefix' => 'travel', 'as' => 'travel.'], function () {
    //     Route::get('/', 'travelController@index')->name('index');


    // });

    // Route::group(['prefix' => 'pesan', 'as' => 'pesan.'], function () {
    //     Route::get('/', 'pesanController@index')->name('index');


    // });
});

Auth::routes();

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');

Route::namespace('admin')->middleware('auth:admin')->group(function () {

    Route::group(['prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/', 'homeController@index')->name('home');
        
    });

    Route::group(['prefix' => 'profile','as' => 'profile.'], function(){
        Route::get('/', 'profileController@index')->name('index');
        Route::post('{profile}/update', 'profileController@update')->name('update');
        
    });

    Route::group(['prefix' => 'soal','as' => 'soal.'], function(){
        Route::get('/', 'soalController@index')->name('index');
        Route::get('/pertanyaan/{id}', 'soalController@edit')->name('pertanyaanIndex');
        Route::post('/pertanyaanUpdate/{id}', 'soalController@update')->name('pertanyaanUpdate');
    });

    // Route::group(['prefix' => 'admin', 'as' => 'galeryAdmin.'], function () {

    //     Route::get('/', 'galeryController@index')->name('index');
    //     Route::post('/store', 'galeryController@store')->name('store');
    //     Route::post('{galeryAdmin}/update', 'galeryController@update')->name('update');
    //     Route::post('{galeryAdmin}/delete', 'galeryController@delete')->name('delete');


    // });
});
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/admin/soalController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Mapel;
use App\Model\kunciJawaban;
use App\Model\Pertanyaan;
use App\Model\pilihanGanda;
use Carbon\Carbon;

class soalController extends Controller{
  
    public function index(){
        $soal = Mapel::all();
        return view('admin.soal.index', compact('soal'));
    }

    public function create(){
       
    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }

    public function edit($id){
        $pertanyaan = Pertanyaan::where('idMapel', $id)->first();
        $pertanyaan2 = Pertanyaan::where('idMapel', $id)->get();
        return view('admin.soal.pertanyaanIndex', compact('pertanyaan','pertanyaan2'));
    }

    public function update(Request $request, $id){
       

        for($i=0;$i<count($request->pilgan1);$i++){
            $pilgan = new pilihanGanda();
            $pilgan->A = $request->pilgan1[$i];
            $pilgan->B = $request->pilgan2[$i];
            $pilgan->C = $request->pilgan3[$i];
            $pilgan->D = $request->pilgan4[$i];
            $pilgan->save();

            // pertanyaan
            $pertanyaan = Pertanyaan::where('idMapel', $id)->get();
            $pertanyaan[$i]->idPilgan = $pilgan->id;
            $pertanyaan[$i]->pertanyaan = $request->soal[$i];
            $pertanyaan[$i]->kunciJawaban = $request->kunciJawaban[$i];
            $pertanyaan[$i]->save();
                
        }


  

       


        
        //kunci 
        // $kunci = kunciJawaban::where('id', $id)->first();
        // $kunci->kunci1 = $request->kunci1;
        // $kunci->kunci2 = $request->kunci2;
        // $kunci->save();

        return redirect(route('soal.index'));

    }

    public function destroy($id){
        
    }
}

resources/views/admin/soal/a.blade.php
<form role="form" action="{{ route('soal.pertanyaanUpdate', $pertanyaan->idMapel) }}" method="POST">
						{{ csrf_field() }}
							<div id="looping">
								<div class="row">
									<div class="col-md-12">
										<label class="bmd-label-floating">Soal No 1</label>
										<div class="form-group">
											<textarea rows="3" type="text" class="form-control" name="soal[]" value="">{{old('soal1', $pertanyaan->pertanyaan1)}}</textarea>
											@if($errors->has('soal1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('soal1') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan A</label>
											<input type="text" class="form-control" name="pilgan1[]" value="">
											@if($errors->has('pilgan1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('pilgan1') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan B</label>
											<input type="text" class="form-control" name="pilgan2[]" value="">
											@if($errors->has('soal1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('soal1') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan C</label>
											<input type="text" class="form-control" name="pilgan3[]" value="">
											@if($errors->has('soal1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('soal1') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan D</label>
											<input type="text" class="form-control" name="pilgan4[]" value="">
											@if($errors->has('soal1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('soal1') }}</strong>
												</span>
											@endif
										</div>
										<!-- <div class="form-group">
											<label class="bmd-label-floating">Kunci Jawaban:</label>
											<input type="text" class="form-control" name="kunci[]" value="">
											@if($errors->has('soal1'))
												<span class="help-block text-danger">
												<strong>{{$errors->first('soal1') }}</strong>
												</span>
											@endif
										</div> -->
									</div>
									<input type="hidden" name="keterangan[]" value="pilgan1"/>
								</div><br><br><br><hr>
							</div>
							<button type="submit" class="btn btn-primary pull-right">Update</button>
							<div class="clearfix"></div>
						</form>
@section('extrascript')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
<script>
	$(document).ready(function(){
		var $no = 2;

		$("#add").click(function(){
			$("#looping").append('<div class="row"><div class="col-md-12"><label class="bmd-label-floating">Soal No'+$no+'</label><div class="form-group"><textarea rows="3" type="text" class="form-control" name="soal[]" value="">{{old("soal1", $pertanyaan->pertanyaan1)}}</textarea>    </div></div></div>');
			$no++
		});
	});
</script>
@endsection

resources/views/admin/soal/index.blade.php
@extends('admin.layouts.app')
@section('content')
@section('soal', 'active')
	<div class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-header card-header-primary">
							<h4 class="card-title ">Simple Table</h4>
							<p class="card-category"> Here is a subtitle for this table</p>
						</div>
						<div class="card-body">
							<div class="table-responsive">
								<table class="table">
									<thead class=" text-primary">
										<th>No</th>
										<th>Nama Mapel</th>
										<th>Action</th>
									</thead>
									<tbody>
										@foreach($soal as $soals)
											<tr>
												<td>{{ $loop->iteration }}</td>
												<td>{{ $soals->nama }}</td>
												<td>
													<a href="{{ route('soal.pertanyaanIndex', $soals->id) }}" class="btn btn-info btn-fab btn-fab-mini btn-round"><i class="material-icons">create</i></a>
												</td>
											</tr>
										@endforeach
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/soal/pertanyaanIndex.blade.php
@extends('admin.layouts.app')
@section('content')
@section('soal', 'active')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary">
						<h4 class="card-title">{{ $pertanyaan->mapel()->first()->nama }}</h4>
					</div><br><br>
					<div class="card-body">
						<form role="form" action="{{ route('soal.pertanyaanUpdate', $pertanyaan->idMapel) }}" method="POST">
						{{ csrf_field() }}
							<div id="looping">
								@for($i=0; $i<50; $i++)
								<div class="row">
									<div class="col-md-12">
										<div class="card-header card-header-primary">
											<h4 class="card-title">Soal No {{ $i+1 }}</h4>
										</div><br>
										<label class="bmd-label-floating">Soal</label>
										<div class="form-group">
											<textarea rows="3" type="text" class="form-control" name="soal[]" required>{{ $pertanyaan2[$i]->pertanyaan}}</textarea>
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan A</label>
											<input type="text" class="form-control" name="pilgan1[]" required value="{{ $pertanyaan2[$i]->pilgan()->first()->A }}">
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan B</label>
											<input type="text" class="form-control" name="pilgan2[]" required value="{{ $pertanyaan2[$i]->pilgan()->first()->B }}">
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan C</label>
											<input type="text" class="form-control" name="pilgan3[]" required value="{{ $pertanyaan2[$i]->pilgan()->first()->C }}">
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Pilihan D</label>
											<input type="text" class="form-control" name="pilgan4[]" required value="{{ $pertanyaan2[$i]->pilgan()->first()->D }}">
										</div>
										<div class="form-group">
											<label class="bmd-label-floating">Kunci Jawaban:</label>
											<input type="text" class="form-control" name="kunciJawaban[]" required value="{{ $pertanyaan2[$i]->kunciJawaban}}">
										</div>
									</div>
								</div>
								<br><br><br><hr>
								@endfor
							</div>
							<button type="submit" class="btn btn-primary pull-right">Update</button>
							<div class="clearfix"></div>
						</form>
					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('extrascript')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>