routes/web.php
<?php


Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    // Route::group(['prefix' => 'travel', 'as' => 'travel.'], function () {
    //     Route::get('/', 'travelController@index')->name('index');


    // });

    // Route::group(['prefix' => 'pesan', 'as' => 'pesan.'], function () {
    //     Route::get('/', 'pesanController@index')->name('index');


    // });
});

Auth::routes();

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');

Route::namespace('admin')->middleware('auth:admin')->group(function () {

    Route::group(['prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/', 'homeController@index')->name('home');
        
    });

    Route::group(['prefix' => 'profile','as' => 'profile.'], function(){
        Route::get('/', 'profileController@index')->name('index');
        Route::post('{profile}/update', 'profileController@update')->name('update');
        
    });

    Route::group(['prefix' => 'soal','as' => 'soal.'], function(){
        Route::get('/', 'soalController@index')->name('index');
        Route::get('/pertanyaan/{id}', 'soalController@edit')->name('pertanyaanIndex');
        Route::post('/pertanyaanUpdate/{id}', 'soalController@update')->name('pertanyaanUpdate');
    });

    // Route::group(['prefix' => 'admin', 'as' => 'galeryAdmin.'], function () {

    //     Route::get('/', 'galeryController@index')->name('index');
    //     Route::post('/store', 'galeryController@store')->name('store');
    //     Route::post('{galeryAdmin}/update', 'galeryController@update')->name('update');
    //     Route::post('{galeryAdmin}/delete', 'galeryController@delete')->name('delete');


    // });
});
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/admin/profileController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Repositories\UserRepository;
use Hash;
use Auth;

class profileController extends Controller{

    public function index(){        
        $profile = User::find(Auth::user()->id);
		return view('admin.profile.index',compact('profile'));
    }

    public function update(Request $request, $id){
        $detail = User::find($id);
        $validate = [
            'name' => 'required|max:191',
            'username' => 'required|max:191',
            'email' => 'required|max:191',
            'password' => 'required|max:191',
          
        ];
        
        $this->validate(request(), $validate);
        $detail->name = $request->get('name');
        $detail->email = $request->get('email');
        $detail->username = $request->get('username');
        $detail->password = Hash::make($request->get('password'));
        $detail->save();
        \Session::flash('notif-success', 'Update data berhasil');
        return redirect()->route('profile.index')->with('success', 'Successfully created.');
    }
}

resources/views/admin/profile/index.blade.php
@extends('admin.layouts.app')
@section('content')
@section('profile', 'active')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-primary">
						<h4 class="card-title">Edit Profile</h4>
					</div>
					<div class="card-body">
						<form role="form" action="{{route('profile.update', $profile->id)}}" method="POST">
						{{ csrf_field() }}
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label class="bmd-label-floating">Name</label>
										<input type="text" class="form-control" name="name" value="{{old('name', $profile->name)}}">
										@if($errors->has('name'))
											<span class="help-block text-danger">
											<strong>{{$errors->first('name') }}</strong>
											</span>
										@endif
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label class="bmd-label-floating">NPSN</label>
										<input type="number" class="form-control" max="10000000000" min="0" name="username" value="{{old('username', $profile->username) }}">
										@if($errors->has('username'))
											<span class="help-block text-danger">
											<strong>{{$errors->first('username') }}</strong>
											</span>
										@endif
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label class="bmd-label-floating">Email</label>
										<input type="email" class="form-control" name="email" value="{{old('email', $profile->email) }}">
										@if($errors->has('email'))
											<span class="help-block text-danger">
											<strong>{{$errors->first('email') }}</strong>
											</span>
										@endif
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label class="bmd-label-floating">Password</label>
										<input type="password" class="form-control" name="password">
										@if($errors->has('password'))
											<span class="help-block text-danger">
											<strong>{{$errors->first('password') }}</strong>
											</span>
										@endif
									</div>
								</div>
							</div>
							<button type="submit" class="btn btn-primary pull-right">Update</button>
							<div class="clearfix"></div>
						</form>
					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection