routes/web.php
<?php


Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    // Route::group(['prefix' => 'travel', 'as' => 'travel.'], function () {
    //     Route::get('/', 'travelController@index')->name('index');


    // });

    // Route::group(['prefix' => 'pesan', 'as' => 'pesan.'], function () {
    //     Route::get('/', 'pesanController@index')->name('index');


    // });
});

Auth::routes();

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');

Route::namespace('admin')->middleware('auth:admin')->group(function () {

    Route::group(['prefix' => 'admin','as' => 'admin.'], function(){
        Route::get('/', 'homeController@index')->name('home');
        
    });

    Route::group(['prefix' => 'profile','as' => 'profile.'], function(){
        Route::get('/', 'profileController@index')->name('index');
        Route::post('{profile}/update', 'profileController@update')->name('update');
        
    });

    Route::group(['prefix' => 'soal','as' => 'soal.'], function(){
        Route::get('/', 'soalController@index')->name('index');
        Route::get('/pertanyaan/{id}', 'soalController@edit')->name('pertanyaanIndex');
        Route::post('/pertanyaanUpdate/{id}', 'soalController@update')->name('pertanyaanUpdate');
    });

    // Route::group(['prefix' => 'admin', 'as' => 'galeryAdmin.'], function () {

    //     Route::get('/', 'galeryController@index')->name('index');
    //     Route::post('/store', 'galeryController@store')->name('store');
    //     Route::post('{galeryAdmin}/update', 'galeryController@update')->name('update');
    //     Route::post('{galeryAdmin}/delete', 'galeryController@delete')->name('delete');


    // });
});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('assets/admin/img/apple-icon.png')}}">
    <link rel="icon" type="image/png" href="{{asset('assets/admin/img/favicon.png')}}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
       Admin || Simulasi
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="{{asset('assets/admin/css/material-dashboard.css?v=2.1.1')}}" rel="stylesheet" />
    <link href="{{asset('assets/admin/demo/demo.css')}}" rel="stylesheet" />
</head>
@yield('extrahead')
<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="purple" data-background-color="white" data-image="{{asset('assets/admin/img/sidebar-1.jpg')}}">
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Admin
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="nav-item @yield('dashboard')">
                        <a class="nav-link" href="{{route('admin.home')}}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="nav-item @yield('profile')">
                        <a class="nav-link" href="{{route('profile.index')}}">
                            <i class="material-icons">person</i>
                            <p>Profile</p>
                        </a>
                    </li>
                    <li class="nav-item @yield('soal')">
                        <a class="nav-link" href="{{ route('soal.index') }}">
                            <i class="material-icons">content_paste</i>
                            <p>Soal</p>
                        </a>
                    </li>
                    <li class="nav-item active-pro ">
                        <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="material-icons">exit_to_app</i>
                            <p>Keluar</p>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidde">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            @yield('content')
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="float-left">
                        <ul>
                            <li>
                                <a href="https://www.creative-tim.com">
                                    Creative Tim
                                </a>
                            </li>
                            <li>
                                <a href="https://creative-tim.com/presentation">
                                    About Us
                                </a>
                            </li>
                            <li>
                                <a href="http://blog.creative-tim.com">
                                    Blog
                                </a>
                            </li>
                            <li>
                                <a href="https://www.creative-tim.com/license">
                                    Licenses
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright float-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>, made with <i class="material-icons">favorite</i> by
                        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="{{asset('assets/admin/js/core/jquery.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/core/popper.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/core/bootstrap-material-design.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/moment.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/sweetalert2.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/jquery.validate.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/jquery.bootstrap-wizard.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/bootstrap-selectpicker.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/bootstrap-datetimepicker.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/bootstrap-tagsinput.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/jasny-bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/fullcalendar.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/jquery-jvectormap.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/nouislider.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
    <script src="{{asset('assets/admin/js/plugins/arrive.min.js')}}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <script src="{{asset('assets/admin/js/plugins/chartist.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/plugins/bootstrap-notify.js')}}"></script>
    <script src="{{asset('assets/admin/js/material-dashboard.js?v=2.1.1')}}" type="text/javascript"></script>
    <script src="{{asset('assets/admin//demo/demo.js')}}"></script>
    <script>
        $(document).ready(function() {
            $().ready(function() {
                $sidebar = $('.sidebar');

                $sidebar_img_container = $sidebar.find('.sidebar-background');

                $full_page = $('.full-page');

                $sidebar_responsive = $('body > .navbar-collapse');

                window_width = $(window).width();

                fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

                if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
                    if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
                        $('.fixed-plugin .dropdown').addClass('open');
                    }

                }

                $('.fixed-plugin a').click(function(event) {
                    if ($(this).hasClass('switch-trigger')) {
                        if (event.stopPropagation) {
                            event.stopPropagation();
                        } else if (window.event) {
                            window.event.cancelBubble = true;
                        }
                    }
                });

                $('.fixed-plugin .active-color span').click(function() {
                    $full_page_background = $('.full-page-background');

                    $(this).siblings().removeClass('active');
                    $(this).addClass('active');

                    var new_color = $(this).data('color');

                    if ($sidebar.length != 0) {
                        $sidebar.attr('data-color', new_color);
                    }

                    if ($full_page.length != 0) {
                        $full_page.attr('filter-color', new_color);
                    }

                    if ($sidebar_responsive.length != 0) {
                        $sidebar_responsive.attr('data-color', new_color);
                    }
                });

                $('.fixed-plugin .background-color .badge').click(function() {
                    $(this).siblings().removeClass('active');
                    $(this).addClass('active');

                    var new_color = $(this).data('background-color');

                    if ($sidebar.length != 0) {
                        $sidebar.attr('data-background-color', new_color);
                    }
                });

                $('.fixed-plugin .img-holder').click(function() {
                    $full_page_background = $('.full-page-background');

                    $(this).parent('li').siblings().removeClass('active');
                    $(this).parent('li').addClass('active');


                    var new_image = $(this).find("img").attr('src');

                    if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                        $sidebar_img_container.fadeOut('fast', function() {
                            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                            $sidebar_img_container.fadeIn('fast');
                        });
                    }

                    if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                        var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                        $full_page_background.fadeOut('fast', function() {
                            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                            $full_page_background.fadeIn('fast');
                        });
                    }

                    if ($('.switch-sidebar-image input:checked').length == 0) {
                        var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                        var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                        $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                        $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                    }

                    if ($sidebar_responsive.length != 0) {
                        $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
                    }
                });

                $('.switch-sidebar-image input').change(function() {
                    $full_page_background = $('.full-page-background');

                    $input = $(this);

                    if ($input.is(':checked')) {
                        if ($sidebar_img_container.length != 0) {
                            $sidebar_img_container.fadeIn('fast');
                            $sidebar.attr('data-image', '#');
                        }

                        if ($full_page_background.length != 0) {
                            $full_page_background.fadeIn('fast');
                            $full_page.attr('data-image', '#');
                        }

                        background_image = true;
                    } else {
                        if ($sidebar_img_container.length != 0) {
                            $sidebar.removeAttr('data-image');
                            $sidebar_img_container.fadeOut('fast');
                        }

                        if ($full_page_background.length != 0) {
                            $full_page.removeAttr('data-image', '#');
                            $full_page_background.fadeOut('fast');
                        }

                        background_image = false;
                    }
                });

                $('.switch-sidebar-mini input').change(function() {
                    $body = $('body');

                    $input = $(this);

                    if (md.misc.sidebar_mini_active == true) {
                        $('body').removeClass('sidebar-mini');
                        md.misc.sidebar_mini_active = false;

                        $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

                    } else {

                        $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

                        setTimeout(function() {
                            $('body').addClass('sidebar-mini');

                            md.misc.sidebar_mini_active = true;
                        }, 300);
                    }

                    // we simulate the window Resize so the charts will get updated in realtime.
                    var simulateWindowResize = setInterval(function() {
                        window.dispatchEvent(new Event('resize'));
                    }, 180);

                    // we stop the simulation of Window Resize after the animations are completed
                    setTimeout(function() {
                        clearInterval(simulateWindowResize);
                    }, 1000);

                });
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            md.initDashboardPageCharts();

        });
    </script>
    @yield('extrascript')
</body>
</html>